server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver


  output.ansi.enabled: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create # create, update, none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect:
        default_schema:
    defer-datasource-initialization: true


  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zome: Asia/Seoul


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

